# Generated by Django 3.1.4 on 2021-06-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210608_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='user',
        ),
    ]
