# Generated by Django 3.1.4 on 2021-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_doctors_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='service',
        ),
        migrations.AddField(
            model_name='appointments',
            name='date_issued',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
