# Generated by Django 3.1.4 on 2021-06-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20210608_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
