# Generated by Django 3.1.4 on 2021-06-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_doctors_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
