# Generated by Django 3.1.4 on 2021-06-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20210608_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
