# Generated by Django 3.1.4 on 2021-06-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_patients_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
